### ISSUE TITLE
About specific training setting and result

### ISSUE THREAD

**Issue by byydzh** [lzfff12/HFL-Net#4]
First thanks for your nice work. Personally, I have tried retraining it myself and got results, but this result differs especially on dexycb from the pretrained checkpoint you provided (approximately 13.0 vs 12.5 difference for hand mpjpe). So I wonder if there is a difference between the specific setup of your training and the code in this github repository. Or some tricks when you're training. Or maybe it's simply me doing something wrong? I need your opinion.
Also, if possible, please tell me your training speed, because I feel that my training speed is a bit slow, no noticeable improvement using multiple GPUs :(

**Comment by lzfff12** [comment]
Could you please provide your training log？

**Comment by byydzh** [comment]
This is an excerpt from the final training log. The 30th epoch got my best results so far.

> (epoch: 21, time: Mon Aug 28 05:14:33 2023),mano_mesh3d_loss:0.56421959400177,mano_joints3d_loss:0.6118496060371399,manopose_loss:0.06303597241640091,manoshape_loss:0.012497954070568085,mano_total_loss:1.251601219177246,hm_joints2d_loss:0.3266577124595642,obj_reg_loss:13.142823219299316,obj_conf_loss:5.150577545166016,total_loss:19.87166976928711
> (epoch: 22, time: Mon Aug 28 09:22:35 2023),mano_mesh3d_loss:0.5697338581085205,mano_joints3d_loss:0.617871880531311,manopose_loss:0.06308114528656006,manoshape_loss:0.012668409384787083,mano_total_loss:1.2633557319641113,hm_joints2d_loss:0.32816416025161743,obj_reg_loss:13.130609512329102,obj_conf_loss:5.151484966278076,total_loss:19.87361717224121
> (epoch: 23, time: Mon Aug 28 13:28:18 2023),mano_mesh3d_loss:0.5596593618392944,mano_joints3d_loss:0.6067551374435425,manopose_loss:0.06297169625759125,manoshape_loss:0.01249255146831274,mano_total_loss:1.2418770790100098,hm_joints2d_loss:0.3271181285381317,obj_reg_loss:13.095869064331055,obj_conf_loss:5.141373157501221,total_loss:19.806299209594727
> (epoch: 24, time: Mon Aug 28 17:34:46 2023),mano_mesh3d_loss:0.5654496550559998,mano_joints3d_loss:0.613152801990509,manopose_loss:0.06298645585775375,manoshape_loss:0.01258180569857359,mano_total_loss:1.2541712522506714,hm_joints2d_loss:0.32723286747932434,obj_reg_loss:13.070322036743164,obj_conf_loss:5.141510486602783,total_loss:19.793231964111328
> (epoch: 25, time: Mon Aug 28 21:42:29 2023),mano_mesh3d_loss:0.5610176920890808,mano_joints3d_loss:0.6083277463912964,manopose_loss:0.06297147274017334,manoshape_loss:0.01245938241481781,mano_total_loss:1.244775652885437,hm_joints2d_loss:0.32663649320602417,obj_reg_loss:13.053585052490234,obj_conf_loss:5.137335300445557,total_loss:19.76230812072754
> (epoch: 26, time: Tue Aug 29 01:49:35 2023),mano_mesh3d_loss:0.5624205470085144,mano_joints3d_loss:0.6098882555961609,manopose_loss:0.0629023015499115,manoshape_loss:0.01260045450180769,mano_total_loss:1.247809648513794,hm_joints2d_loss:0.32668569684028625,obj_reg_loss:12.972967147827148,obj_conf_loss:5.125511646270752,total_loss:19.6729679107666
> (epoch: 27, time: Tue Aug 29 05:56:12 2023),mano_mesh3d_loss:0.5511921048164368,mano_joints3d_loss:0.5976462364196777,manopose_loss:0.06274016946554184,manoshape_loss:0.012560510076582432,mano_total_loss:1.2241383790969849,hm_joints2d_loss:0.32509753108024597,obj_reg_loss:12.882796287536621,obj_conf_loss:5.106976509094238,total_loss:19.539020538330078
> (epoch: 28, time: Tue Aug 29 10:03:00 2023),mano_mesh3d_loss:0.5414783954620361,mano_joints3d_loss:0.5870814919471741,manopose_loss:0.062479596585035324,manoshape_loss:0.012527230195701122,mano_total_loss:1.203568935394287,hm_joints2d_loss:0.3216937780380249,obj_reg_loss:12.776309967041016,obj_conf_loss:5.086483955383301,total_loss:19.388036727905273
> (epoch: 29, time: Tue Aug 29 14:14:03 2023),mano_mesh3d_loss:0.532738983631134,mano_joints3d_loss:0.5776264071464539,manopose_loss:0.06232483312487602,manoshape_loss:0.01249623205512762,mano_total_loss:1.1851849555969238,hm_joints2d_loss:0.32020559906959534,obj_reg_loss:12.626604080200195,obj_conf_loss:5.057769298553467,total_loss:19.189777374267578
> (epoch: 30, time: Tue Aug 29 18:25:08 2023),mano_mesh3d_loss:0.5071078538894653,mano_joints3d_loss:0.5498970746994019,manopose_loss:0.061502087861299515,manoshape_loss:0.012422643601894379,mano_total_loss:1.130930781364441,hm_joints2d_loss:0.31273767352104187,obj_reg_loss:12.296185493469238,obj_conf_loss:4.991159915924072,total_loss:18.73102569580078
> (epoch: 31, time: Tue Aug 29 22:37:46 2023),mano_mesh3d_loss:0.5774219036102295,mano_joints3d_loss:0.6261529326438904,manopose_loss:0.06331527978181839,manoshape_loss:0.012555225752294064,mano_total_loss:1.279443621635437,hm_joints2d_loss:0.3297980725765228,obj_reg_loss:13.553336143493652,obj_conf_loss:5.2083234786987305,total_loss:20.37091827392578

**Comment by byydzh** [comment]
I found that there was an error in my code. After the modification, I retrained and got results that were closer to the official results. Therefore, this problem has been solved. Thank you for your attention.

**Comment by rookiiiie** [comment]
> I found that there was an error in my code. After the modification, I retrained and got results that were closer to the official results. Therefore, this problem has been solved. Thank you for your attention.

Hello, I have also encountered some similar difficulties. Can you share me how you solve it?

Also,have you conducted training on the HO3D dataset and obtained corresponding results, if you do,have you encountered any difficulties when training

I am looking forward to your reply，thank you！
