### ISSUE TITLE
你好，我复现不出原论文的效果

### ISSUE THREAD

**Issue by rookiiiie** [lzfff12/HFL-Net#7]
在HO3D数据集上，按照你的论文中的参数设置，原模原样的代码任何配置都没有修改，测试集上的结果如下：
Evaluation 3D KP results:
auc=0.047, mean_kp3d_avg=10638.99 cm
Evaluation 3D KP PROCRUSTES ALIGNED results:
auc=0.775, mean_kp3d_avg=1.13 cm
Evaluation 3D KP SCALE-TRANSLATION ALIGNED results:
auc=0.407, mean_kp3d_avg=3.92 cm

Evaluation 3D MESH results:
auc=0.000, mean_kp3d_avg=10192.54 cm
Evaluation 3D MESH ALIGNED results:
auc=0.778, mean_kp3d_avg=1.11 cm

F-scores
F@5.0mm = 0.000 	F_aligned@5.0mm = 0.453
F@15.0mm = 0.000 	F_aligned@15.0mm = 0.929

各个评价指标都与原论文所宣称的差距较大，请问这是为什么？

**Comment by kyxxc** [comment]
Hello, I would like to ask you how you successfully reproduced the code

I encountered this error during the replication process and was unable to find/data1/zhifeng/hoddv2/evaluation. txt . May I ask if you encountered this situation while running the code?

Looking forward to your reply

**Comment by rookiiiie** [comment]
> Hello, I would like to ask you how you successfully reproduced the code
> 
> I encountered this error during the replication process and was unable to find/data1/zhifeng/hoddv2/evaluation. txt . May I ask if you encountered this situation while running the code?
> 
> Looking forward to your reply

u need to replace the path with your own path,it locate in dataset HO3D

**Comment by kyxxc** [comment]
Hello, it's an honor to receive your reply. I am a graduate student from Liaoning, China. I would like to add your contact information to discuss this code. Finally, I sincerely wish you and your family good health

**Comment by kyxxc** [comment]
I have conducted research on the baseline paper of this article and have made some breakthroughs. I would like to share with you the updated methods. Thank you
